import io
import csv
import time
from datetime import datetime, timedelta

import boto3
from flask import current_app

from backend.services import summary_service


def get_s3_client(endpoint_url=None):
    config = current_app.config
    return boto3.client(
        's3',
        endpoint_url=endpoint_url or config['S3_ENDPOINT_URL'],
        region_name=config['S3_REGION'],
        aws_access_key_id=config['AWS_ACCESS_KEY_ID'],
        aws_secret_access_key=config['AWS_SECRET_ACCESS_KEY'],
    )


def ensure_bucket_exists(client):
    bucket = current_app.config['S3_BUCKET_NAME']
    try:
        client.head_bucket(Bucket=bucket)
    except client.exceptions.ClientError:
        client.create_bucket(Bucket=bucket)
        client.put_bucket_cors(
            Bucket=bucket,
            CORSConfiguration={
                'CORSRules': [{
                    'AllowedHeaders': ['*'],
                    'AllowedMethods': ['GET'],
                    'AllowedOrigins': ['*'],
                    'MaxAgeSeconds': 3600,
                }]
            },
        )


def _get_daily_summaries(user_id, start_date, end_date):
    summaries = []
    current = start_date
    while current <= end_date:
        summaries.append(summary_service.get_daily_summary(user_id, current))
        current += timedelta(days=1)
    return summaries


def generate_csv_content(user, daily_summaries, start_date, end_date):
    buf = io.StringIO()
    buf.write(f"# CalorieMind Export | {start_date} to {end_date}\n")
    buf.write(
        f"# User: {user.name or 'N/A'} | "
        f"Weight: {user.weight or 'N/A'}kg | "
        f"Height: {user.height or 'N/A'}cm | "
        f"Age: {user.age or 'N/A'} | "
        f"Goal: {user.goal} | "
        f"Target: {user.daily_calorie_target or 'N/A'} kcal | "
        f"BMR: {user.calculate_bmr() or 'N/A'} kcal\n"
    )
    writer = csv.writer(buf)
    writer.writerow([
        'Date', 'Calories Consumed', 'Calories Burned', 'Net Calories',
        'Protein (g)', 'Carbs (g)', 'Fats (g)', 'Fiber (g)', 'Sugar (g)',
        'Sodium (mg)', 'Meals', 'Activities',
    ])
    for s in daily_summaries:
        writer.writerow([
            s['date'].isoformat() if hasattr(s['date'], 'isoformat') else s['date'],
            s['calories_consumed'], s['calories_burned'], s['net_calories'],
            s['protein'], s['carbs'], s['fats'], s['fiber'], s['sugar'],
            s['sodium'], s['meals_count'], s['activities_count'],
        ])
    return buf.getvalue()


def generate_txt_content(user, daily_summaries, start_date, end_date):
    buf = io.StringIO()
    sep = '=' * 60
    line = '-' * 60
    bmr = user.calculate_bmr()

    buf.write(f"{sep}\n")
    buf.write("  CalorieMind Data Export\n")
    buf.write(f"  Period: {start_date} to {end_date}\n")
    buf.write(f"{sep}\n\n")

    buf.write("USER PROFILE\n")
    buf.write(f"  Name:           {user.name or 'N/A'}\n")
    buf.write(f"  Weight:         {user.weight or 'N/A'} kg\n")
    buf.write(f"  Height:         {user.height or 'N/A'} cm\n")
    buf.write(f"  Age:            {user.age or 'N/A'}\n")
    buf.write(f"  Goal:           {user.goal}\n")
    buf.write(f"  Daily Target:   {user.daily_calorie_target or 'N/A'} kcal\n")
    buf.write(f"  BMR:            {bmr or 'N/A'} kcal\n\n")

    for s in daily_summaries:
        d = s['date']
        if hasattr(d, 'strftime'):
            day_label = d.strftime('%Y-%m-%d (%A)')
        else:
            day_label = str(d)
        buf.write(f"{line}\n")
        buf.write(f"  {day_label}\n")
        buf.write(f"{line}\n")
        buf.write(f"  Calories Consumed:  {s['calories_consumed']:>6}\n")
        buf.write(f"  Calories Burned:    {s['calories_burned']:>6}\n")
        buf.write(f"  Net Calories:       {s['net_calories']:>6}\n")
        buf.write(f"  Protein:          {s['protein']:>6.1f} g\n")
        buf.write(f"  Carbs:            {s['carbs']:>6.1f} g\n")
        buf.write(f"  Fats:             {s['fats']:>6.1f} g\n")
        buf.write(f"  Fiber:            {s['fiber']:>6.1f} g\n")
        buf.write(f"  Sugar:            {s['sugar']:>6.1f} g\n")
        buf.write(f"  Sodium:           {s['sodium']:>6.1f} mg\n")
        buf.write(f"  Meals:            {s['meals_count']:>6}\n")
        buf.write(f"  Activities:       {s['activities_count']:>6}\n\n")

    today = datetime.utcnow().strftime('%Y-%m-%d')
    buf.write(f"{sep}\n")
    buf.write(f"  Generated by CalorieMind on {today}\n")
    buf.write(f"{sep}\n")
    return buf.getvalue()


def export_data(user, start_date, end_date, fmt):
    config = current_app.config

    daily_summaries = _get_daily_summaries(user.id, start_date, end_date)

    if fmt == 'csv':
        content = generate_csv_content(user, daily_summaries, start_date, end_date)
        content_type = 'text/csv'
    else:
        content = generate_txt_content(user, daily_summaries, start_date, end_date)
        content_type = 'text/plain'

    ext = fmt
    filename = f"export_{start_date}_{end_date}.{ext}"
    key = f"{user.id}/{int(time.time())}_{start_date}_{end_date}.{ext}"
    bucket = config['S3_BUCKET_NAME']

    # Upload using internal endpoint
    upload_client = get_s3_client()
    ensure_bucket_exists(upload_client)
    upload_client.put_object(
        Bucket=bucket,
        Key=key,
        Body=content.encode('utf-8'),
        ContentType=content_type,
    )

    # Generate presigned URL using public endpoint (for browser access)
    public_endpoint = config.get('S3_PUBLIC_ENDPOINT_URL')
    if public_endpoint:
        presign_client = get_s3_client(endpoint_url=public_endpoint)
    else:
        presign_client = upload_client

    download_url = presign_client.generate_presigned_url(
        'get_object',
        Params={'Bucket': bucket, 'Key': key},
        ExpiresIn=config['EXPORT_URL_EXPIRY'],
    )

    return {
        'download_url': download_url,
        'filename': filename,
        'format': fmt,
    }
