name: Infrastructure Setup

on:
  workflow_dispatch:

jobs:
  infra:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Apply
        run: |
          cd infra
          terraform init -reconfigure -input=false
          terraform apply -auto-approve
          EC2_IP=$(terraform output -raw ec2_public_ip | tr -d '\n\r')
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Update DuckDNS record
        run: |
          echo "Updating DuckDNS..."
          echo "EC2_IP=[$EC2_IP]"
          curl "https://www.duckdns.org/update?domains=caloriemind&token=${{ secrets.DUCKDNS_TOKEN }}&ip=$EC2_IP"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

      - name: Wait for SSH
        run: |
          until ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "echo SSH ready"; do
            sleep 5
          done

      - name: Generate Ansible inventory
        run: |
          cat > ansible/inventory.ini <<EOF
          [web]
          $EC2_IP ansible_user=ubuntu
          EOF

      - name: Run Ansible (Docker + Nginx + HTTPS)
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/setup.yml --private-key ~/.ssh/id_rsa
          ansible-playbook -i ansible/inventory.ini ansible/nginx.yml --private-key ~/.ssh/id_rsa
